export const ADD_INGREDIENTS = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'
export const DISPATCH_INGREDIENTS = 'DISPATCH_INGREDIENTS'
export const FEATCH_FAILED_INGREDIENTS = 'FEATCH_FAILED_INGREDIENTS'